### ISSUE TITLE
Customer Can Create Product 

### ISSUE THREAD

**Issue by danirenae** [Ludicrous-Ducks/Bangazon_django#11]
## Feature Description

A customer should be able to create a product to sell

## Story

As Bangazon customer/user
in order to create a product to sell 
I want that products have a product name, description, and price
in order for other users/customers to find and purchase the products

## Scenarios

Given that I'm a user or customer of Bangazon
When I click the `Add a Product` button on the product page
Then I want the to be able to fill out name, description and price for a price

## What should the feature do?

Registered and logged in Users/Customers should be able to seamlessly add a product to sell to other Bangazon users/customers

## When and where should the feature appear?

The feature appears on the Product page

## Potential Impact on Code or Other Features

The Product Create code may impact other code that outputs products to the DOM

**Comment by juliakimchung** [comment]
closed by PR
