### ISSUE TITLE
User Login & Registration 

### ISSUE THREAD

**Issue by shawn-mit** [Ludicrous-Ducks/Bangazon_django#17]
//////////////README.MD ////////////////////////////

Index.html Django template to create  : 
1.User login and registration 

### Feature Description:
A customer should be able to either Login to Banagazon or Register as a new customer of Bangazon.

### Story

*As a visitor* to the Bangazon website
*In order to* purchase products
*I want to* login or register with Bangazon

### Scenarios

*Given* that I'm a new user of Bangazon
*When* I visit the website
*Then* I want to be able to register an account with pertnient information 
*Or* If I'm already a registered user 
*When* I click on the login button 
*Then* I want to be sent to the product 'View' page

### Context

1. What should the feature do?
- Allow new shoppers register or login with Bangazon.

2. When and where should the feature appear?
Upon visiting the website , user must login or register.

**Comment by juliakimchung** [comment]
closed by PR
