### ISSUE TITLE
Registration Template

### ISSUE THREAD

**Issue by shawn-mit** [Ludicrous-Ducks/Bangazon_django#22]
## Expected Behavior
-This template will provide  the UI with a registration view for the new user

## Actual Behavior
- 

## Steps to Reproduce Behavior 
- Attempt to register as a new user with Bangazon  

## Module Suspected / Relevant Files 
- registration.html

## Related Issues 
- index.html template

**Comment by ben-d-marks** [comment]
Need more field to reflect customer model
