### ISSUE TITLE
URL Routings for login,register, create product, create product type, list product type

### ISSUE THREAD

**Issue by shawn-mit** [Ludicrous-Ducks/Bangazon_django#26]
## Expected Behavior
- The user is able to navigate to different views of Bangazon for Login and Registration

## Actual Behavior
- 

## Steps to Reproduce Behavior 
- Register as a new user and then logout 
- As a registered user attempt to login to Bangazon 

## Module Suspected / Relevant Files 
- bangazon_ui / urls.py

## Related Issues 
-  templates/

**Comment by juliakimchung** [comment]
closed by PR
