### ISSUE TITLE
Product Type List Page restyle

### ISSUE THREAD

**Issue by ben-d-marks** [Ludicrous-Ducks/Bangazon_django#82]
## Expected Behavior
On the product_type page when navigated from the nav bar, the top 10 list of the most recent product type created will display

## Actual Behavior
When you click the product_type_list from the nav bar, It will display the most recent 10 of product_types with () next to each product_type. inside of (), it will display how many products are available with the integer value

## Steps to Reproduce Behavior 

On the product_type_list view, create a query that lists out the most recently created 10 product type

## Related Issues 

#81

**Comment by juliakimchung** [comment]
product type list is being displayed with 10 products under each product type.
product type is listed as the latest  10 lists created
