### ISSUE TITLE
Orders can have Payment Type

### ISSUE THREAD

**Issue by shawn-mit** [Ludicrous-Ducks/Bangazon_django#9]
////////README.MD ////////////////////// 
The Order model must have a foreign key field to the PaymentType model, but it can be nullable. However, before an order can be completed, there must be a value for the PaymentType field.

### Feature Description:
A customer should be able to shop with a default payment type set for the customer.

### Story

*As a visitor* to the Bangazon website
*In order to* browse products  and shop
*I want to* have a default payment type 

### Scenarios

*Given* that I'm a registered user of Bangazon
*and* logged in to the system
*and* I have an incomplete (unpaid) order
*When* I click the `Add to Order` button on a _Product Details_ page
*Then* I would like to have a default payment type selected

1. What should the feature do?
- Registered and logged Users should be able to shop with a default payment type selected

2. When and where should the feature appear?
The feature appears on every incomplete Order

**Comment by ben-d-marks** [comment]
fixed by #67
